%--------------------------------------------------------------------------
%
% Show logos in the four corners of a plot 
%
%--------------------------------------------------------------------------

% Running under Matlab or Octave
if exist ('OCTAVE_VERSION', 'builtin')
    system = 'Octave';
    warning("off", "Octave:shadowed-function");
else
    system = 'Matlab';
end

% setting three strings
string1 = 'String 1';
string2 = 'This is the second string which is quite long';
string3 = 'Shorter third string';

% height of screen
screen = get (0, 'ScreenSize');          % Screen size
s_height = screen(4);

% specify the fonts
f_name = 'Helvetica';
f_small = round(s_height/125)-2;
f_large = round(s_height/125);
f_heavy = 'bold';

% specify line/curve styles
l_thin  = 1;
l_thick = 2;
pattern = '-';

% position and size of plot window
w_left   = round(  s_height/16);         % Left border
w_lower  = round(  s_height/16);         % Lower border
w_width  = round(  s_height);            % Width
w_height = round(9*s_height/16);         % Height
w_width =  2*round(w_width /2);          % Should be even
w_height = 2*round(w_height/2);          % Should be even

% create figure window
if strcmpi(system,'Matlab')
    h1 = figure(1);    % Under Octave, this opens a window in default size
    set(h1, ...        % Under Octave, this redraws window in desired size
        'units','pixels', ...
        'position',[w_left w_lower w_width w_height] );
elseif strcmpi(system,'Octave')
    h1 = figure(1,...  % unfortunately, this syntax is not allowed in Matlab
        'units','pixels', ...
        'position',[w_left w_lower w_width w_height] );
end

%% Annotations

% Upper left
h = annotation('textbox');
set(h, ...
    'Position',            [0.0 0.5 0.5 0.5], ... % [left bottom width height]
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment',   'top', ...
    'Interpreter',         'none', ...
    'LineStyle',           'none', ...
    'String',              { string1, string2, string3 }, ...
    'FontName',            f_name, ...
    'FontSize',            f_small, ...
    'FontWeight',          f_heavy, ...
    'FitBoxToText',        'off')

% Upper right
h = annotation('textbox');
set(h, ...
    'Position',            [0.5 0.5 0.5 0.5], ... % [left bottom width height]
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment',   'top', ...
    'Interpreter',         'none', ...
    'LineStyle',           'none', ...
    'String',              { string1, string2, string3 }, ...
    'FontName',            f_name, ...
    'FontSize',            f_small, ...
    'FontWeight',          f_heavy, ...
    'FitBoxToText',        'off')

% Lower left
h = annotation('textbox');
set(h, ...
    'Position',            [0.0 0.01 0.5 0.5], ... % [left bottom width height]
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment',   'bottom', ...
    'Interpreter',         'none', ...
    'LineStyle',           'none', ...
    'String',              { string1, string2 }, ...
    'FontName',            f_name, ...
    'FontSize',            f_small, ...
    'FontWeight',          f_heavy, ...
    'FitBoxToText',        'off')

% Lower right
h = annotation('textbox');
set(h, ...
    'Position',            [0.5 0.01 0.5 0.5], ... % [left bottom width height]
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment',   'bottom', ...
    'Interpreter',         'none', ...
    'LineStyle',           'none', ...
    'String',              { string1, string2 }, ...
    'FontName',            f_name, ...
    'FontSize',            f_small, ...
    'FontWeight',          f_heavy, ...
    'FitBoxToText',        'off')


%% Contour plots
x = linspace(-10,10, 201);
y = linspace(-05,05, 101);
[X,Y] = meshgrid(x,y);

cnt_min = 0.01;
cnt_max = 0.9;
cnt_nlv  = 20;
color = [0.9290 0.6940 0.1250];

for i=1:10
    F = (X+5-i).^2/7 + (Y+2-i/2).^2/7;
    contour(X,Y,F, ...
        'LevelList', linspace(cnt_min, cnt_max, cnt_nlv), ...
        'LineStyle', pattern, ...
        'LineWidth', l_thick, ...
        'LineColor', color)
    
    title(['Contour plot : ' int2str(i)])
    xlabel('x-axis')
    ylabel('y-axis')
    
    set(gca, ...
        'LineWidth',  l_thick, ...
        'FontName',   f_name, ...
        'FontSize',   f_large, ...
        'FontWeight', f_heavy)
    
    drawnow
    pause(0.5)
    
end

%% Curve plots
x = linspace(-10,10, 201);
for i=1:20
    
    f = exp(-(x+5-i/2).^2/7).^2;
    plot(x,f, ...
        'LineStyle', pattern, ...
        'LineWidth', l_thick, ...
        'Color', color)
    
    title(['Curve plot : ' int2str(i)])
    xlabel('x-axis')
    ylabel('y-axis')
    
    set(gca, ...
        'LineWidth',  l_thick, ...
        'FontName',   f_name, ...
        'FontSize',   f_large, ...
        'FontWeight', f_heavy)
    
    drawnow
    
end


