% Plot three control functionals during iteration
% (1) Target
% (2) Costs
% (3) Total
%
%
% This file is part of the WavePacket program package for quantum-mechanical
% simulations, and subject to the GNU General Public license v. 2 or later.
%
% Copyright (C) 2015-16 Burkhard Schmidt
%
% see the README file for license details.

function plot_j12 ( iter )

global control info plots

% Initialize figure; draw logos, and resize
if iter==1
    if strcmpi(info.system,'Matlab')
        h = figure(8);
        set(h, ...
            'Name','Target & cost functionals', ...
            'units','pixels', ...
            'position',[ ...
            plots.control.w_left+plots.control.w_width*1.1 ...
            plots.control.w_lower ...
            plots.control.w_width ...
            plots.control.w_height] );
    elseif strcmpi(info.system,'Octave')
        figure(8, ...
            'Name','Target & cost functionals', ...
            'units','pixels', ...
            'position',[ ...
            plots.control.w_left+plots.control.w_width*1.1 ...
            plots.control.w_lower ...
            plots.control.w_width ...
            plots.control.w_height] );
    end
    show_logo (plots.control);
else
    figure(8)
end

% Top: target functional
subplot(3,1,1)
plot(1:iter,control.j.target(1:iter),'o', ...
    'LineStyle',    '-', ...
    'LineWidth',    plots.control.l_thin)
set ( gca, ...
    'LineWidth',    plots.control.l_thick, ...
    'FontName',     plots.control.f_name,  ...
    'FontSize',     plots.control.f_large, ...
    'FontWeight',   plots.control.f_heavy )
xlabel('iterations')
ylabel('target J_1')
title (control.title);

% Middle: Cost functional
subplot(3,1,2)
plot(1:iter,control.j.cost(1:iter),'o', ...
    'LineStyle',    '-', ...
    'LineWidth',    plots.control.l_thin)
set ( gca, ...
    'LineWidth',    plots.control.l_thick, ...
    'FontName',     plots.control.f_name,  ...
    'FontSize',     plots.control.f_large, ...
    'FontWeight',   plots.control.f_heavy )
xlabel('iterations')
ylabel('cost J_2')

% Bottom: Total functional
subplot(3,1,3)
plot(1:iter,control.j.total(1:iter),'o', ...
    'LineStyle',    '-', ...
    'LineWidth',    plots.control.l_thin)
hold on
plot(1:iter,control.j.addup(1:iter),'o', ...
    'LineStyle',    ':', ...
    'LineWidth',    plots.control.l_thin)
hold off
xlabel('iterations')
ylabel('optimize total')
set ( gca, ...
    'LineWidth',    plots.control.l_thick, ...
    'FontName',     plots.control.f_name,  ...
    'FontSize',     plots.control.f_large, ...
    'FontWeight',   plots.control.f_heavy )

% Update figure window
drawnow

saveas (8,'j12.fig')
saveas (8,'j12.jpg')

